let initialized = false;

export function init() {
  if (initialized) return;
  initialized = true;
  'use strict';
   const KEY='st-magic-wand-organizer';
   let st=Object.assign({theme:'auto',favorites:[],category:'全部',search:''},JSON.parse(localStorage.getItem(KEY)||'{}'));
   const save=()=>localStorage.setItem(KEY,JSON.stringify(st));
   const $=(s,r=document)=>r.querySelector(s);
   const $$=(s,r=document)=>[...r.querySelectorAll(s)];
   const txt=e=>(e?.innerText||e?.textContent||e?.title||'').replace(/\s+/g,' ').trim();
   const btn=()=>$('#extensionsMenuButton')||$$('button,[role=button]').find(e=>/extension|扩展|魔棒|magic|wand/i.test((e.id||'')+' '+(e.title||'')+' '+(e.getAttribute('aria-label')||'')));
   const menu=()=>$('#extensionsMenu')||$('[id*=extensionsMenu]')||$('.extensionsMenu');
   const cats=[['💬 聊天',/翻译|朗读|聊天|输入|备忘录/],['🖼 图片',/图片|图库|绘|头像|照片/],['🔊 多媒体',/TTS|朗读|播放器|音频|视频/],['🛠 管理',/管理|变量|日志|数据|备份|正则|Token|提示词|收纳|楼层/]];
   const cat=n=>(cats.find(x=>x[1].test(n))||['⚙️ 其他'])[0];
   const ico=n=>{const a=[[/附件/,'📎'],[/图库|图片/,'🖼️'],[/生成图片|绘/,'🎨'],[/翻译/,'🌐'],[/朗读|TTS/,'🔊'],[/Token/,'🔢'],[/楼层/,'🏢'],[/美化/,'🎨'],[/变量/,'🧮'],[/日志/,'📜'],[/提示词/,'🔎'],[/备忘录/,'📝'],[/主题/,'🌙'],[/书摘/,'🔖'],[/正则/,'⌁']];return(a.find(x=>x[0].test(n))||[0,'✨'])[1]};
   const items=()=>{const m=menu();return m?[...m.children].filter(e=>txt(e)&&!e.classList.contains('mwo-ignore')).map(e=>({el:e,name:txt(e),cat:cat(txt(e)),icon:ico(txt(e))})):[]};
   let ov,grid,search,catsEl,count,theme;
   function styles(){if($('#mwo-style'))return;const s=document.createElement('style');s.id='mwo-style';s.textContent='#mwo-overlay{--bg:#fafafd;--card:#f0f1f6;--input:#fff;--text:#20222a;--muted:#777b87;--border:#d9dce5;--accent:#7657f5;--icon:#e8e3ff;--star:#d99b00;position:fixed;inset:0;z-index:2147483640;display:none;align-items:center;justify-content:center;padding:10px;background:#0007;backdrop-filter:blur(8px)}#mwo-overlay.dark{--bg:#17181e;--card:#23252d;--input:#202128;--text:#f4f4f6;--muted:#a5a8b2;--border:#393c47;--accent:#987cff;--icon:#302951;--star:#ffd45b}#mwo-panel{width:min(720px,96vw);height:min(82vh,780px);display:flex;flex-direction:column;overflow:hidden;border:1px solid var(--border);border-radius:24px;background:var(--bg);color:var(--text);box-shadow:0 28px 80px #0007;font-family:system-ui,-apple-system,'Microsoft YaHei',sans-serif}#mwo-head{display:flex;align-items:center;gap:9px;padding:15px 16px 9px}.mwo-title{font-weight:800;font-size:20px;flex:1}.mwo-sub{font-size:11px;color:var(--muted);margin-top:2px}.mwo-btn{width:40px;height:40px;border:1px solid var(--border);border-radius:12px;background:var(--card);color:var(--text);font-size:18px;cursor:pointer}#mwo-search{margin:0 16px 10px;height:45px;border:1px solid var(--border);border-radius:14px;background:var(--input);color:var(--text);padding:0 14px;font-size:15px;outline:0}#mwo-cats{display:flex;gap:7px;overflow:auto;padding:0 16px 11px}.mwo-cat{white-space:nowrap;padding:8px 12px;border-radius:999px;border:1px solid var(--border);background:transparent;color:var(--text);cursor:pointer}.mwo-cat.on{background:var(--accent);border-color:var(--accent);color:#fff}#mwo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;overflow:auto;padding:3px 16px 16px}.mwo-card{position:relative;min-height:72px;padding:11px 38px 10px 11px;border:1px solid var(--border);border-radius:17px;background:var(--card);color:var(--text);text-align:left;cursor:pointer}.mwo-card:hover{border-color:var(--accent)}.mwo-icon{width:38px;height:38px;border-radius:12px;background:var(--icon);display:flex;align-items:center;justify-content:center;font-size:21px;margin-bottom:6px}.mwo-name{font-weight:700;font-size:14px}.mwo-meta{font-size:10px;color:var(--muted);margin-top:4px}.mwo-star{position:absolute;right:7px;top:7px;border:0;background:transparent;color:var(--star);font-size:19px;cursor:pointer}#mwo-foot{margin-top:auto;border-top:1px solid var(--border);padding:8px 12px;display:flex;color:var(--muted);font-size:11px}#mwo-count{flex:1}@media(max-width:520px){#mwo-overlay{align-items:flex-end;padding:0}#mwo-panel{width:100%;height:88vh;border-radius:23px 23px 0 0}}@media(max-width:340px){#mwo-grid{grid-template-columns:1fr}}';document.head.appendChild(s)}
   function build(){styles();ov=document.createElement('div');ov.id='mwo-overlay';ov.className=st.theme;ov.innerHTML='<div id=mwo-panel><div id=mwo-head><div class=mwo-title>🪄 魔棒快捷菜单<div class=mwo-sub>搜索 · 分类 · 收藏 · 日夜模式</div></div><button id=mwo-theme class=mwo-btn>🌓</button><button id=mwo-close class=mwo-btn>×</button></div><input id=mwo-search placeholder="🔍 搜索工具…"><div id=mwo-cats></div><div id=mwo-grid></div><div id=mwo-foot><span id=mwo-count></span><span>⭐ 收藏 · Esc 关闭</span></div></div>';document.body.appendChild(ov);grid=$('#mwo-grid');search=$('#mwo-search');catsEl=$('#mwo-cats');count=$('#mwo-count');theme=$('#mwo-theme');$('#mwo-close').onclick=close;theme.onclick=cycle;ov.onclick=e=>{if(e.target===ov)close()};search.oninput=()=>{st.search=search.value;save();render()};render()}
   function cycle(){st.theme=st.theme==='auto'?'light':st.theme==='light'?'dark':'auto';save();ov.className=st.theme;theme.textContent=st.theme==='dark'?'☀️':st.theme==='light'?'🌙':'🌓'}
   function render(){const all=items(),q=st.search.toLowerCase().trim(),cs=['全部','⭐ 常用','💬 聊天','🖼 图片','🔊 多媒体','🛠 管理','⚙️ 其他'];catsEl.innerHTML='';cs.forEach(c=>{const b=document.createElement('button');b.className='mwo-cat'+(st.category===c?' on':'');b.textContent=c;b.onclick=()=>{st.category=c;save();render()};catsEl.appendChild(b)});const vs=all.filter(x=>(st.category==='全部'||(st.category==='⭐ 常用'?st.favorites.includes(x.name):x.cat===st.category))&&(!q||x.name.toLowerCase().includes(q)));grid.innerHTML='';if(!vs.length)grid.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:45px;color:var(--muted)">没有找到工具</div>';vs.forEach(x=>{const c=document.createElement('div');c.className='mwo-card';c.innerHTML='<div class=mwo-icon>'+x.icon+'</div><div class=mwo-name></div><div class=mwo-meta></div><button class=mwo-star></button>';$('.mwo-name',c).textContent=x.name;$('.mwo-meta',c).textContent=x.cat;$('.mwo-star',c).textContent=st.favorites.includes(x.name)?'★':'☆';$('.mwo-star',c).onclick=e=>{e.stopPropagation();st.favorites=st.favorites.includes(x.name)?st.favorites.filter(n=>n!==x.name):st.favorites.concat(x.name);save();render()};c.onclick=()=>{try{x.el.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}))}catch{try{x.el.click()}catch{}}close()};grid.appendChild(c)});count.textContent='共 '+all.length+' 个工具 · ⭐ '+st.favorites.length+' 个收藏'}
   function open(){if(!ov)build();render();ov.style.display='flex';setTimeout(()=>search&&search.focus(),20)}
   function close(){if(ov)ov.style.display='none'}
   let hooked=false;function hook(){const b=btn(),m=menu();if(!b||!m)return false;if(!hooked){b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();open()},true);hooked=true}m.style.display='none';if(!ov)build();return true}
   new MutationObserver(hook).observe(document.documentElement,{subtree:true,childList:true});let n=0,t=setInterval(()=>{if(hook()||++n>180)clearInterval(t)},500);window.MagicWandOrganizer={open,close,inspect:()=>{const b=btn(),m=menu();return{buttonFound:!!b,buttonId:b?.id||'',menuFound:!!m,menuId:m?.id||'',menuChildren:m?.children?.length||0}}};
}
